sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - tests/geckodriver.sh
  - export PATH=$PATH:$PWD
install:
  - pip install tox-travis
script:
  - tox
after_success:
env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest
