language: python
python:
  - 2.6
  - 2.7
  - 3.2
install:
  - pip install nose
  - pip install webob
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.5' ]]; then pip install paste; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install paste; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install paste; fi"
  - python setup.py develop
script:
  - nosetests -s -v
